audit_header: false
title: The Real Estate Raw Show
description: Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET -- real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The -- CLIENT BRAND --, your professional -- MARKET -- Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: Joe Mendoza
  title:
  license_number: CA DRE 01234540
  about_markdown: |
    Joe Mendoza has been involved in real estate for over 20 years. He has been a Real Estate Broker, Investor, Consultant, Advisor, Mentor, Managing Partner, Acquisitions Manager, and a Nationwide Coach. At present, he is President of the Joe Mendoza Team, Inc. San Diego, California. Mr. Mendoza also is an Executive Real Estate and Business Coach for Tom Ferry Your Coach, based in Newport Beach, CA.

    Mr. Mendoza has a long track record of success. While at Prudential California Realty, he ranked as high as the Top 1% in the nation and was number 7 in all of San Diego County. He built a team of 2 full-time employees and 5 licensed associate agents.
  market: San Diego
  brand: Katcam Real Estate
  brokerage:
  address: 100 E. San Marcos Boulevard, Suite 400<br>San Marcos, CA 92069
  phone: 877-794-5227
  phone_type: Toll-Free 24/7
  phone2: 619-246-4663
  phone2_type: Direct
  email: joe@joemendoza.com
  url: http://JoeMendozaTeam.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://joemendoza.com/
  second_CTA_text: Home Search
  second_CTA_URL: https://www.homesnap.com/Joe-Mendoza

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "What’s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: http://joemendoza.com/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://www.homesnap.com/Joe-Mendoza

sponsor:
  header_text: 'Sponsored by:'
  headshot_path: http://fillmurray.com/200/200
  logo_path1: /img/sponsors/logo1.png
  url_path1: http://www.katcamrealestate.com/
  logo_path2: /img/sponsors/logo2.png
  url_path2: http://www.mccormicknationalholdings.com/
  logo_path3: /img/sponsors/logo3.png
  url_path3: http://affiliates.patlive.com/joe-mendoza-team/
  logo_path4: /img/sponsors/logo4.png
  url_path4: http://www.ezfundings.com/
  logo_path5: /img/sponsors/logo5.png
  url_path5: https://www.colerealtyresource.com/landing/joemendoza/
  logo_path6: /img/sponsors/logo6.png
  url_path6: https://mortgage.bankofamerica.com/83913


socials:
  review_sm_icons: false
  facebook_url:
  linkedin_url:
  gplus_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url: https://itunes.apple.com/us/podcast/san-diego-real-estate-podcast-with-joe-mendoza/id1072155610?mt=2

podcast:
  title: The Real Estate Raw Show with Joe Mendoza
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 55
  hero_text: The Real Estate Raw Show with Joe Mendoza
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#636825'
  brand_dark_color: '#2B6CA4'
  brand_light_color: '#2B6CA4'
  theme_color: '#231f20'
  theme_text_color: '#5d9bd3'
  main_body_color: '#B7CCDF'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
